### ISSUE TITLE
Add URL in the sidebar

### ISSUE THREAD

**Issue by core-man** [gmt-china/sitepreview#1]
https://gmt-china.github.io/sitepreview/

**Comment by seisman** [comment]
I don't get it.

**Comment by wangliang1989** [comment]
他意思是说他想把这个链接加到手册的左边的目录里

**Comment by seisman** [comment]
Why do we want the preview link in the sidebar?

**Comment by wangliang1989** [comment]
先睹为快

**Comment by seisman** [comment]
The preview link is posted for each PR. I don't think we should add it to the sidebar.

**Comment by wangliang1989** [comment]
我是猜测他的意思，还要他自己来解释

**Comment by core-man** [comment]
https://github.com/gmt-china/sitepreview 的说明部分下面：
> Repository for continuous documentation deployment. DO NOT COMMIT DIRECTLY TO THIS REPOSITORY UNLESS YOU KNOW WHAT YOU ARE DOING!

see https://github.com/seismo-learn/sitepreview

我没有修改权限

**Comment by wangliang1989** [comment]
啥意思？

**Comment by core-man** [comment]
> 啥意思？

完成了，仓库右边说明部分加了url了。
